import Head from 'next/head'
import Image from 'next/image'
import { ConnectButton } from 'web3uikit'
import LotteryEntrance from '../components/LotteryEntrance'
import styles from '../styles/Home.module.css'

export default function Home() {
  const styles = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#BBE6F260',
    padding: '10px',
    marginBottom:'30px'
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={styles}>
          <h2>Hello Web3</h2>

          <ConnectButton moralisAuth={false} />

        </div>

        <LotteryEntrance />
      </main>

    </div>
  )
}
